### ISSUE TITLE
Newlines need to be unified

### ISSUE THREAD

**Issue by FichteFoll** [skuroda/PackageResourceViewer#10]
When reading files using the load_resource API you need to unify newline handling because literal \r characters are displayed in ST if not handles on file load. I imagine that OS 9 line endings with just \r would result in a single line in ST.

Example: `view.run_command("insert", {"characters": "\r"})`

This can result in the following:

![2015-03-06_19 35 25](https://cloud.githubusercontent.com/assets/931051/6531248/024a31a4-c438-11e4-84f5-744ff949d8e3.png)

Example file is `bh_core.sublime-settings` in the BracketHighlighter package.

**Comment by skuroda** [comment]
Pushed a fix in fed0aa8. Thanks for using PackageResourceViewer.
