### ISSUE TITLE
Not appearing in package control

### ISSUE THREAD

**Issue by xaun** [skuroda/PackageResourceViewer#13]
![screen shot 2016-08-11 at 9 55 42 am](https://cloud.githubusercontent.com/assets/7486451/17575102/d196a5c4-5fa9-11e6-8c1c-29e086e4cfbf.png)

Not sure why... but this package isnt appearing in my package control O_o ?

**Comment by Ekkstein** [comment]
Hm, having the same issue. What am I missing?

**Comment by Ekkstein** [comment]
Yeah...quite obvious...it's installed already!

**Comment by skuroda** [comment]
That would be a good reason :)
