### ISSUE TITLE
Extract all official packages (feature request)

### ISSUE THREAD

**Issue by marcospb19** [skuroda/PackageResourceViewer#24]
When I saw `Extract All Packages`, I wanted to use it, but only for the non-official packages installed using the `Package Control: Install package` command

I want to suggest 2 new commands, in addition to `Extract All Packages`, and I'm willing to make the Pull Request if you like the feature idea.

`Extract All Official Packages`
`Extract All Non-Official Packages`

Official packages include all packages that come with sublime by default, you can see them installing `PackageResourceViewer` after a clean install of sublime, and seeing the list that appears when you select `Extract All Packages`.

Here's the list of official packages, adding `print(len(self.packages) , self.packages)` on `package_resource_viewer.py`, line `379` after installing `Package Control` and `PackageResourceViewer`:

`51 ['ASP', 'ActionScript', 'AppleScript', 'Batch File', 'C#', 'C++', 'CSS', 'Clojure', 'Color Scheme - Default', 'Color Scheme - Legacy', 'D', 'Default', 'Diff', 'Erlang', 'Git Formats', 'Go', 'Graphviz', 'Groovy', 'HTML', 'Haskell', 'Java', 'JavaScript', 'LaTeX', 'Language - English', 'Lisp', 'Lua', 'Makefile', 'Markdown', 'Matlab', 'OCaml', 'Objective-C', 'PHP', 'Package Control', 'Pascal', 'Perl', 'Python', 'R', 'Rails', 'Regular Expressions', 'RestructuredText', 'Ruby', 'Rust', 'SQL', 'Scala', 'ShellScript', 'TCL', 'Text', 'Textile', 'Theme - Default', 'XML', 'YAML']`

PackageResourceViewer is not listed because it was already extracted.

**Comment by marcospb19** [comment]
`Extract All Non-Official Packages` would perform similarly to `Extract All Packages`, but i would just filter out the Official packages, that can be stored in a separated file to save some RAM, or it could be a list at the start of the `.py` file.

**Comment by marcospb19** [comment]
Let me know if this Pull Request would be welcome, i want to participate to the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) this year. :D

**Comment by skuroda** [comment]
I apologize for the delay. I've been enjoying a break from the internet for
the last several days. Yes a PR is always welcome!

**Comment by marcospb19** [comment]
I still use this extension, but I think this feature does not make sense anymore for my use cases, if you're ok with it I'm closing this one.

Thanks!
