### ISSUE TITLE
Extracting Package Control breaks it

### ISSUE THREAD

**Issue by marcospb19** [skuroda/PackageResourceViewer#25]
When extracting via "Extract All Packages" the Package Control breaks and I'm unable to install or remove any package.

Steps to reproduce:
1 - Install `Package Control`
2 - Install `PackageResourceViewer`
3 - `Extract All Packages` using `PackageResourceViewer`

And then this popup will show every time Sublime is opened.

![image](https://user-images.githubusercontent.com/38900226/66496471-580e4b00-ea91-11e9-8f15-2adee1ee46bf.png)

**Comment by marcospb19** [comment]
I am also willing to fix this issue, what is the best approach to do this?

I thought of just blocking the extraction of `Package Control`.

Alternatively, we could change the name of the extracted package so it don't conflict, but this would be very confusing for the users that were trying to make changes and see them.

**Comment by skuroda** [comment]
I think we should create a preference around packages to not unpackage. By
default it'll just be package control, but will give us a mechanism to
extend that in the future. We also can't rename the extracted package as
sublime would treat that as two separate plugins.

**Comment by marcospb19** [comment]
> I think we should create a preference around packages to not unpackage. By
default it'll just be package control, but will give us a mechanism to
extend that in the future.

Alright, I'll try to implement this already in this month, the list will stay inside of PackageResourceViewer.sublime-settings, it is a .json file without the extension name.

Then we just insert the list there.

For reference the preferences for C++, see `Open Resource` -> `C++` -> `C++.sublime-settings`.

**Comment by marcospb19** [comment]
`Resending this comment.`

> I think we should create a preference around packages to not unpackage. By
default it'll just be package control, but will give us a mechanism to
extend that in the future.

Alright, I'll try to implement this already in this month, the list will stay inside of PackageResourceViewer.sublime-settings.
