### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by alberti42** [skuroda/PackageResourceViewer#27]
Great package. I had found an issue with the missing path. On Mac I get the error:
```
[Errno 2] No such file or directory: 'make -j1 juko'
[cmd: make -j1 juko]
```
I solved the issue by changing `cmd` into `shell_cmd` in `targets.py`:
```
self.window.run_command('exec', dict(
         shell_cmd=cmd,
         file_regex=args.get('file_regex', FILE_REGEX),
         syntax=args.get('syntax', SYNTAX),
         working_dir=args.get('working_dir', Expand(WORKING_DIR, self.window))
      ))
```
The original `Makefile` package does indeed use `shell_cmd` and not `cmd`. Could you consider revert back to `shell_cmd`? Is there any other reason for not doing so?

**Comment by skuroda** [comment]
Hi @alberti42, I don't actively maintain this plugin anymore. If your change is backwards compatible and works cross system, feel free to create a PR and I'll merge it in.

**Comment by alberti42** [comment]
Hi Scott! Thank you for the quick answer. I know the burden of receiving a lot of requests for old software one has written. I am relatively new to sublime. I will monitor my change for a while before a pull request. I think it is quite inoffensive change because it only changes 'cmd' into 'shell_cmd' to execute `make` process, but let's see.

**Comment by skuroda** [comment]
@alberti42 I suppose I should have done this before, but think you might have pulled up the wrong plugin for your particular error. There's no `targets.py` in this repo :)

**Comment by alberti42** [comment]
Hi Scott, I am embarrassed I posted to the wrong plugin. Thank you for your plugin PackageResourceViewer which quite helped me and did not give me any trouble! Great work.

**Comment by skuroda** [comment]
No problem at all! I should have checked too! :) Will close out this ticket then.
