### ISSUE TITLE
Can't find in Package Control

### ISSUE THREAD

**Issue by manuelmeurer** [skuroda/PackageResourceViewer#9]
I'm trying to find PackageResourceViewer in Package Control but can't.
![](http://content.screencast.com/users/manuel.meurer/folders/Jing/media/5d6a631e-374c-4d7e-8be4-5d7379fbbc5e/00000294.png)
I'm running ST3 build 3065.

**Comment by skuroda** [comment]
Hmm, that's odd. Is it possible that you had previously installed it? I would check "Package Control: List Packages" and the ignored packages list in Users/Preferences.sublime-settings to be sure. If it's not in either list, then this may be a bug with package control.

**Comment by manuelmeurer** [comment]
Haha, yeah, I have it already installed... sorry!

**Comment by jcrben** [comment]
I can't find it either. Note that it says "Removed" on PackageControl: https://packagecontrol.io/packages/PackageResourceViewer

**Comment by skuroda** [comment]
@jcrben I see it on the package control site. It's possible package control had a hiccup. Please check again.

**Comment by jcrben** [comment]
Looks like that must have been it - the removed label is gone and I installed the package. Thanks for the great work!
